"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,testserver").split(
    ","
)

if DEBUG:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "10.0.0.218",
    ]


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # CORS headers
    "corsheaders",
    # Ninja API
    "ninja_extra",
    # Django Allauth
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.mfa",
    # 'allauth.usersessions',  # Disabled - incompatible with signed_cookies sessions
    "identity",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # CSRF middleware removed - JWT authentication is inherently CSRF-safe
    # (tokens sent in Authorization header, not cookies)
    "identity.middleware.LoginFlushMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

AUTH_USER_MODEL = "identity.User"

# Security settings

# HSTS (HTTP Strict Transport Security) - forces HTTPS for 1 year after first visit
# In development (DEBUG=True), set to 0 to allow HTTP
# In production (DEBUG=False), set to 1 year (31536000 seconds)
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000

# Prevent MIME-sniffing attacks - browser must respect Content-Type header
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable browser XSS filtering (legacy, but doesn't hurt)
SECURE_BROWSER_XSS_FILTER = True

# Session cookies only sent over HTTPS in production
# In development (DEBUG=True), set to False to allow HTTP
# In production (DEBUG=False), must be True
SESSION_COOKIE_SECURE = not DEBUG

# Allauth settings

ACCOUNT_ADAPTER = "identity.adapter.IdentityAdapter"
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# Email verification - mandatory for production readiness
# In development, can be 'none' for easier testing
# In production, should be 'mandatory' to ensure email validity
ACCOUNT_EMAIL_VERIFICATION = "none" if DEBUG else "mandatory"
# ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
# ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

# Rate limiting for authentication endpoints (brute-force protection)
# Format: "X/Ym" means X attempts per Y minutes
# Limits are per IP address
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/5m",  # 5 failed login attempts per 5 minutes
    "manage_email": "5/1h",  # 5 email management operations per hour
    "reauthenticate": "5/5m",  # 5 re-authentication attempts per 5 minutes
    "reset_password": "3/15m",  # 3 password reset requests per 15 minutes
    "change_password": "5/15m",  # 5 password changes per 15 minutes
}

HEADLESS_ONLY = True

# Enable only app client (JWT-based authentication)
# Disables browser client endpoints (/_allauth/browser/v1/*)
HEADLESS_CLIENTS = ["app"]

# JWT Token Strategy Configuration
# Use asymmetric keys (RS256) so other services can validate tokens without the private key
HEADLESS_TOKEN_STRATEGY = "allauth.headless.tokens.strategies.jwt.JWTTokenStrategy"
HEADLESS_JWT_ALGORITHM = "RS256"

# Load keys from environment or files
# In development: uses local files in config/keys/
# In production: loads from environment variables or secrets management
_jwt_private_key_path = os.environ.get(
    "JWT_PRIVATE_KEY_PATH", BASE_DIR / "config" / "keys" / "jwt_private_key.pem"
)
_jwt_public_key_path = os.environ.get(
    "JWT_PUBLIC_KEY_PATH", BASE_DIR / "config" / "keys" / "jwt_public_key.pem"
)

HEADLESS_JWT_PRIVATE_KEY = Path(_jwt_private_key_path).read_text().strip()
HEADLESS_JWT_PUBLIC_KEY = Path(_jwt_public_key_path).read_text().strip()

# Token expiration times
HEADLESS_JWT_ACCESS_TOKEN_EXPIRES_IN = 300  # 5 minutes
HEADLESS_JWT_REFRESH_TOKEN_EXPIRES_IN = int(
    os.environ.get("JWT_REFRESH_TOKEN_EXPIRES_IN", "1209600")
)  # 14 days (default), configurable via env var
HEADLESS_JWT_ROTATE_REFRESH_TOKEN = True

# Cookie settings for JWT-based authentication
# CSRF protection is no longer needed - JWT tokens are sent in Authorization header
# which is inherently CSRF-safe (not vulnerable to cross-site request forgery)
CSRF_COOKIE_SECURE = False  # Don't rely on CSRF cookies
CSRF_COOKIE_HTTPONLY = False  # Not using CSRF cookies for JWT auth

# Database-backed sessions required for JWT token refresh compatibility.
# allauth's validate_refresh_token() calls session_store().exists(session_key) to verify
# the session. The signed_cookies backend always returns False from exists(), breaking
# token refresh and causing immediate logout after the access token expires.
# LoginFlushMiddleware handles the 409 Conflict issue that arises with db-backed sessions.
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# CORS configuration for API access
CORS_ALLOWED_ORIGINS = [
    "https://digidex.bio",
    "https://www.digidex.bio",
    "https://id.digidex.bio",
    "https://app.digidex.bio",  # App service frontend
    "http://localhost:3000",  # Development (app frontend)
    "http://localhost:5173",  # Development (id frontend)
    "http://127.0.0.1:3000",  # Development (app frontend, loopback)
    "http://127.0.0.1:5173",  # Development (id frontend, loopback)
    "http://10.0.0.218",  # Development via Pi IP
    "http://10.0.0.218:10000",  # Development via Pi IP (Traefik)
]
CORS_ALLOW_CREDENTIALS = True
MFA_SUPPORTED_TYPES = ["totp", "recovery_codes", "webauthn"]
MFA_PASSKEY_LOGIN_ENABLED = True
MFA_PASSKEY_SIGNUP_ENABLED = False

# Social account providers configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

# User sessions tracking disabled - using JWT tokens for auth state instead
USERSESSIONS_TRACK_ACTIVITY = False
