"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,testserver").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Ninja API
    'ninja_extra',

    # Django Allauth
    'allauth',
    'allauth.account',
    'allauth.headless',
    'allauth.socialaccount',
    'allauth.mfa',
    # 'allauth.usersessions',  # Disabled - incompatible with signed_cookies sessions

    'identity',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF middleware removed - JWT authentication is inherently CSRF-safe
    # (tokens sent in Authorization header, not cookies)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

AUTH_USER_MODEL = 'identity.User'

# Allauth settings

ACCOUNT_ADAPTER = 'identity.adapter.IdentityAdapter'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
#ACCOUNT_EMAIL_VERIFICATION_BY_CODE_ENABLED = True
#ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

HEADLESS_ONLY = True

# JWT Token Strategy Configuration
# Use asymmetric keys (RS256) so other services can validate tokens without the private key
HEADLESS_TOKEN_STRATEGY = "allauth.headless.contrib.ninja.token_strategy.JWTTokenStrategy"
HEADLESS_JWT_ALGORITHM = "RS256"

# Load keys from environment or files
# In development: uses local files in config/keys/
# In production: loads from environment variables or secrets management
_jwt_private_key_path = os.environ.get(
    "JWT_PRIVATE_KEY_PATH",
    BASE_DIR / "config" / "keys" / "jwt_private_key.pem"
)
_jwt_public_key_path = os.environ.get(
    "JWT_PUBLIC_KEY_PATH",
    BASE_DIR / "config" / "keys" / "jwt_public_key.pem"
)

HEADLESS_JWT_PRIVATE_KEY = Path(_jwt_private_key_path).read_text().strip()
HEADLESS_JWT_PUBLIC_KEY = Path(_jwt_public_key_path).read_text().strip()

# Token expiration times
HEADLESS_JWT_ACCESS_TOKEN_EXPIRES_IN = 300  # 5 minutes
HEADLESS_JWT_REFRESH_TOKEN_EXPIRES_IN = 86400  # 24 hours
HEADLESS_JWT_ROTATE_REFRESH_TOKEN = True

# Cookie settings for JWT-based authentication
# CSRF protection is no longer needed - JWT tokens are sent in Authorization header
# which is inherently CSRF-safe (not vulnerable to cross-site request forgery)
CSRF_COOKIE_SECURE = False  # Don't rely on CSRF cookies
CSRF_COOKIE_HTTPONLY = False  # Not using CSRF cookies for JWT auth

# JWT-only authentication - sessions stored in signed cookies (no database persistence)
# This prevents 409 Conflict from django-allauth when sessions exist in DB
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# CORS configuration for API access
CORS_ALLOWED_ORIGINS = [
    "https://digidex.bio",
    "https://www.digidex.bio",
    "https://id.digidex.bio",
    "http://localhost:3000",  # Development
    "http://localhost:5173",  # Development
]
CORS_ALLOW_CREDENTIALS = True
MFA_SUPPORTED_TYPES = ["totp", "recovery_codes", "webauthn"]
MFA_PASSKEY_LOGIN_ENABLED = True
MFA_PASSKEY_SIGNUP_ENABLED = False

# User sessions tracking disabled - using JWT tokens for auth state instead
USERSESSIONS_TRACK_ACTIVITY = False